-- migrate:up
-- Seed 52 comprehensive, age-stratified child safety & digital literacy quizzes
INSERT INTO quizzes(
  category, question, option_a, option_b, option_c, option_d,
  correct_answer, age_group, explanation
)
SELECT q.category, q.question, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, age.age_group, q.explanation
FROM (VALUES
  -- 1. Digital Privacy & Passwords (13 questions)
  ('Digital Privacy', 'What is the best way to choose a strong password?', 'Use 123456', 'Combine letters, numbers, and symbols that only you know', 'Use your pet''s name', 'Share it with your best friend', 'Combine letters, numbers, and symbols that only you know', 'Strong passwords keep your account secure and should never be shared with friends.'),
  ('Digital Privacy', 'Who is it safe to share your LittleNet password with?', 'Your best classmate', 'A gamer online offering free coins', 'Only your parent or guardian', 'Anyone who asks politely in chat', 'Only your parent or guardian', 'Only parents or guardians should ever know your login password.'),
  ('Digital Privacy', 'Which piece of information is safe to share publicly online?', 'Your home street address', 'Your favourite drawing topic or hobby', 'Your parent''s phone number', 'Your exact birthday and hospital name', 'Your favourite drawing topic or hobby', 'Hobbies and interests are fun to share, but personal details must stay private.'),
  ('Digital Privacy', 'If an online quiz asks for your real school name and grade, what should you do?', 'Type your school and bus stop', 'Ask a parent or skip the quiz', 'Type your friend''s school', 'Share your classroom number', 'Ask a parent or skip the quiz', 'Never enter your school location into unfamiliar websites or apps.'),
  ('Digital Privacy', 'What should you do before posting a photo of your friend?', 'Post it immediately', 'Ask your friend for permission first', 'Tag all their family members', 'Hide the post from teachers', 'Ask your friend for permission first', 'Always ask for permission before taking or posting photos of friends.'),
  ('Digital Privacy', 'Why should location tagging be turned off on kids photos?', 'It drains battery quickly', 'It tells strangers the exact place where you take pictures', 'It changes the photo colors', 'It deletes the photo after a day', 'It tells strangers the exact place where you take pictures', 'Keeping exact locations off protects your real-world safety.'),
  ('Digital Privacy', 'What is two-factor authentication (2FA)?', 'Using two different passwords', 'An extra security step to prove it is really you logging in', 'Having two accounts on LittleNet', 'Logging in on two phones at once', 'An extra security step to prove it is really you logging in', '2FA adds an important second lock to protect your account.'),
  ('Digital Privacy', 'If someone in a video game promises free items if you give your login details, this is called:', 'A lucky giveaway', 'A phishing scam', 'A game bonus', 'A friendly gift', 'A phishing scam', 'Never give your login details for game items or free rewards.'),
  ('Digital Privacy', 'What should you do if you accidentally share your password with someone?', 'Nothing if they promised to keep it secret', 'Change your password immediately and tell a parent', 'Delete all your posts', 'Create five new accounts', 'Change your password immediately and tell a parent', 'Changing your password right away stops anyone else from accessing your profile.'),
  ('Digital Privacy', 'Is it okay to use public Wi-Fi without asking a parent?', 'Yes, always connect to any free network', 'It is safer to ask a parent first because open networks can be insecure', 'Public Wi-Fi is always 100% encrypted', 'Only if you stream movies', 'It is safer to ask a parent first because open networks can be insecure', 'Unsecured public Wi-Fi can allow others on the same network to intercept traffic.'),
  ('Digital Privacy', 'What is digital footprint?', 'A footprint left in digital sand', 'The trail of information left behind by your online activity', 'The number of followers on your profile', 'The time spent playing online games', 'The trail of information left behind by your online activity', 'Everything you post or search forms your digital footprint.'),
  ('Digital Privacy', 'What should you do if an app asks for permission to use your camera and contacts?', 'Accept all permissions without looking', 'Ask your parent if the app really needs those permissions', 'Deny phone power', 'Turn off Wi-Fi forever', 'Ask your parent if the app really needs those permissions', 'Apps should only have permissions they genuinely need to function.'),
  ('Digital Privacy', 'If you see a "Remember My Password" box on a shared computer at school or library, you should:', 'Check the box', 'Leave it unchecked and log out when done', 'Save your credit card', 'Leave the browser open', 'Leave it unchecked and log out when done', 'Never save passwords on shared or public school devices.'),

  -- 2. Online Kindness & Cyberbullying (13 questions)
  ('Online Kindness', 'What is cyberbullying?', 'Helping classmates with homework online', 'Repeatedly sending mean, hurtful, or threatening messages online', 'Playing online puzzle games with cousins', 'Sharing a funny drawing of a cartoon', 'Repeatedly sending mean, hurtful, or threatening messages online', 'Cyberbullying causes real harm and has zero tolerance on LittleNet.'),
  ('Online Kindness', 'What should you do if you witness someone being bullied in a group chat?', 'Join in with mean emojis', 'Stand up kindly for the person or tell a trusted adult', 'Forward the chat to everyone in school', 'Laugh and stay silent', 'Stand up kindly for the person or tell a trusted adult', 'Being an upstander means supporting others and reporting cruel behavior.'),
  ('Online Kindness', 'How can you show kindness to someone who shared a drawing you don''t love?', 'Comment that it is ugly', 'Encourage their effort or scroll past politely', 'Tell others not to like it', 'Post a crying laughing emoji', 'Encourage their effort or scroll past politely', 'Words have power. Constructive, encouraging feedback makes creators happy.'),
  ('Online Kindness', 'What should you do if a comment on your post hurts your feelings?', 'Retaliate with an even meaner comment', 'Take a screenshot, tell a parent, and block or report the user', 'Delete your entire profile', 'Share their phone number', 'Take a screenshot, tell a parent, and block or report the user', 'LittleNet has built-in report and block tools to keep your space peaceful.'),
  ('Online Kindness', 'Is sending a rumor or gossip about a classmate okay if you didn''t start it?', 'Yes, because you just forwarded it', 'No, spreading rumors is hurtful and wrong', 'Only if you say "no offense"', 'Yes, if it was in disappearing mode', 'No, spreading rumors is hurtful and wrong', 'Sharing rumors spreads pain. Break the chain and do not forward gossip.'),
  ('Online Kindness', 'What does it mean to "think before you post"?', 'Wait 2 hours before opening apps', 'Ask yourself if your post is kind, true, and helpful before sharing', 'Only post when angry', 'Count to 100 while typing', 'Ask yourself if your post is kind, true, and helpful before sharing', 'Taking 5 seconds to think helps prevent posts you might regret later.'),
  ('Online Kindness', 'If a friend asks you to exclude someone from an online group, what is the best response?', 'Agree so you stay popular', 'Suggest including them and explain that excluding hurts', 'Leave school', 'Post a poll about them', 'Suggest including them and explain that excluding hurts', 'Inclusive communities make everyone feel safe and valued.'),
  ('Online Kindness', 'What should you do if someone creates a fake account using your friend''s photo?', 'Make a fake account of that person too', 'Report the impersonation account to the app and tell an adult', 'Ignore it and tell no one', 'Like all its posts', 'Report the impersonation account to the app and tell an adult', 'Impersonation is a violation of LittleNet rules and should be reported.'),
  ('Online Kindness', 'How should you apologize if you accidentally posted something that hurt a classmate?', 'Ignore them and pretend it never happened', 'Reach out sincerely, apologize, and delete the hurtful post', 'Blame your autocorrect', 'Post an angry story', 'Reach out sincerely, apologize, and delete the hurtful post', 'A genuine apology and taking down hurtful content shows maturity.'),
  ('Online Kindness', 'Why are all-caps words (LIKE THIS) often avoided in polite chats?', 'They use too much phone memory', 'They can look like shouting or anger', 'They are harder for robots to read', 'They disable emojis', 'They can look like shouting or anger', 'TYPING IN ALL CAPS often feels like yelling to the reader.'),
  ('Online Kindness', 'What is the Golden Rule of the internet?', 'Always get the most likes', 'Treat others online the way you want to be treated', 'Post 10 times a day', 'Never like anyone''s post', 'Treat others online the way you want to be treated', 'Treating others with respect creates a positive digital world for everyone.'),
  ('Online Kindness', 'If someone sends you a rude message, should you reply immediately while angry?', 'Yes, send whatever you feel', 'No, step away, take a breath, and talk to an adult first', 'Send 50 angry stickers', 'Post their message in a public channel', 'No, step away, take a breath, and talk to an adult first', 'Cooling off prevents conflicts from escalating into bigger problems.'),
  ('Online Kindness', 'What is an "upstander"?', 'Someone who stands up while typing', 'Someone who sees wrongdoing and takes positive action to help', 'Someone with the highest gaming rank', 'A teacher who monitors recess', 'Someone who sees wrongdoing and takes positive action to help', 'Upstanders make social media safe by supporting victims of bullying.'),

  -- 3. Phishing, Scams & Stranger Danger (13 questions)
  ('Cyber Smarts', 'You receive a message saying: "You won an iPad! Click this link to claim!" What should you do?', 'Click immediately and enter your address', 'Recognize it as a scam and tell an adult without clicking', 'Forward it to your whole family', 'Reply asking for two iPads', 'Recognize it as a scam and tell an adult without clicking', 'Unsolicited prize links are classic phishing scams designed to steal data.'),
  ('Cyber Smarts', 'If an online friend you have never met in real life asks to meet up alone, what should you do?', 'Agree to meet at a quiet park', 'Say no, tell your parent immediately, and never go', 'Ask them to bring candy', 'Keep it a secret from parents', 'Say no, tell your parent immediately, and never go', 'Never meet an online stranger in person without a parent.'),
  ('Cyber Smarts', 'A message appears: "Your account will be deleted in 5 minutes unless you verify your password here!" What is this?', 'An official emergency from LittleNet', 'A scare tactic scam trying to steal your login credentials', 'A normal system test', 'A software speed test', 'A scare tactic scam trying to steal your login credentials', 'Legitimate platforms never threaten instant deletion to force password entry.'),
  ('Cyber Smarts', 'What should you do if an online acquaintance asks you to send a private picture of yourself?', 'Send it if they say please', 'Refuse, block them, and tell a trusted adult right away', 'Send an old picture instead', 'Ask them to send one first', 'Refuse, block them, and tell a trusted adult right away', 'Never send private pictures to anyone online. Always inform a trusted adult.'),
  ('Cyber Smarts', 'What does the lock symbol (HTTPS) in a website address bar mean?', 'The website is for kids only', 'The connection between your browser and the website is encrypted', 'The website has no advertisements', 'The computer is locked for bedtime', 'The connection between your browser and the website is encrypted', 'HTTPS secures the data sent between your device and the server.'),
  ('Cyber Smarts', 'If an email claims to be from your teacher but uses strange spelling and a weird address, you should:', 'Download all attachments', 'Check with your teacher in person or ask a parent before opening', 'Reply with your homework passwords', 'Forward it to the principal', 'Check with your teacher in person or ask a parent before opening', 'Phishing emails often disguise themselves as trusted teachers or schools.'),
  ('Cyber Smarts', 'What is malware?', 'A special drawing application', 'Harmful software designed to damage or spy on your device', 'A type of fast internet cable', 'An educational video category', 'Harmful software designed to damage or spy on your device', 'Malware can steal data or harm your phone. Only download trusted apps.'),
  ('Cyber Smarts', 'Why should you avoid downloading free games or movies from unofficial sites?', 'They might contain viruses or dangerous malware', 'They take up zero storage space', 'They make the battery last forever', 'They change the language to French', 'They might contain viruses or dangerous malware', 'Pirated and unofficial download sites are the primary source of malware.'),
  ('Cyber Smarts', 'If a stranger online asks: "Are your parents home right now?", what is the safe response?', 'Say "No, I am home alone"', 'Do not answer, close the chat, and tell your parent immediately', 'Tell them your front door code', 'Tell them which room you are in', 'Do not answer, close the chat, and tell your parent immediately', 'Never share your family''s schedule or whether you are home alone.'),
  ('Cyber Smarts', 'What is "catfishing"?', 'Playing an online game about catching fish', 'When someone creates a fake identity online to deceive others', 'Sending funny cat stickers in comments', 'Fixing a slow computer mouse', 'When someone creates a fake identity online to deceive others', 'People online may not be who they claim to be. Stay cautious.'),
  ('Cyber Smarts', 'If you click a link and your screen suddenly flashes red with loud beeping, what should you do?', 'Call the number on the screen and pay money', 'Close the tab, do not click anything on it, and tell an adult', 'Smash your keyboard', 'Share it with your friends', 'Close the tab, do not click anything on it, and tell an adult', 'Fake virus alerts are designed to panic you into calling scammers.'),
  ('Cyber Smarts', 'What is the best way to back up your important school projects and art?', 'Save them on a piece of paper only', 'Keep a copy in a secure cloud or USB approved by your parents', 'Leave them in the trash bin', 'Take a screenshot on a friend''s phone', 'Keep a copy in a secure cloud or USB approved by your parents', 'Regular backups protect your creative work from accidental loss.'),
  ('Cyber Smarts', 'If someone in a game chat offers you $50 gift cards if you do a chore for them, you should:', 'Accept immediately', 'Decline, report the message, and inform your guardian', 'Ask for $100 instead', 'Give your email address', 'Decline, report the message, and inform your guardian', 'Strangers offering money or gifts online often have dangerous motives.'),

  -- 4. Digital Well-being & Healthy Screen Time (13 questions)
  ('Digital Well-being', 'Why is it important to take regular screen breaks?', 'To give your eyes, body, and brain time to rest', 'Because the phone will melt otherwise', 'To make the internet faster', 'So your battery cools down to 0 degrees', 'To give your eyes, body, and brain time to rest', 'Taking breaks prevents digital eye strain and keeps your mind sharp.'),
  ('Digital Well-being', 'What is the 20-20-20 rule for eye health?', 'Every 20 hours, sleep 20 hours for 20 days', 'Every 20 minutes, look at something 20 feet away for 20 seconds', 'Watch 20 videos on 20 different tablets', 'Read 20 books in 20 minutes', 'Every 20 minutes, look at something 20 feet away for 20 seconds', 'The 20-20-20 rule relaxes your eye muscles while using digital devices.'),
  ('Digital Well-being', 'Why should screens be put away at least 30 minutes before bedtime?', 'Blue light from screens interferes with healthy sleep hormones', 'Screens run out of color at night', 'The internet shuts down globally at night', 'Bedrooms have too much Wi-Fi', 'Blue light from screens interferes with healthy sleep hormones', 'Avoiding screens before bed helps you fall asleep faster and rest deeper.'),
  ('Digital Well-being', 'If you feel tired, grumpy, or anxious after scrolling social media, what is the healthy choice?', 'Keep scrolling for 3 more hours', 'Put the phone down, get fresh air, or do an offline activity', 'Post an angry status update', 'Turn the screen brightness to maximum', 'Put the phone down, get fresh air, or do an offline activity', 'Recognizing digital fatigue and stepping away is a sign of emotional strength.'),
  ('Digital Well-being', 'What does FOMO stand for in social media?', 'Full Of Much Oatmeal', 'Fear Of Missing Out', 'Fast Online Message Option', 'Finding Other Memes Online', 'Fear Of Missing Out', 'FOMO makes people feel anxious about what others are doing. Real life matters most.'),
  ('Digital Well-being', 'Which of these is a great offline hobby to balance your screen time?', 'Reading a book, riding a bicycle, or playing outdoor sports', 'Staring at a blank television', 'Checking notifications every 2 minutes', 'Playing mobile games while walking', 'Reading a book, riding a bicycle, or playing outdoor sports', 'A balanced day includes movement, nature, and offline creativity.'),
  ('Digital Well-being', 'What is a healthy posture when using a tablet or phone?', 'Slouching on your neck for hours', 'Holding the screen near eye level with relaxed shoulders', 'Lying face down on the floor', 'Balancing the phone on your forehead', 'Holding the screen near eye level with relaxed shoulders', 'Keeping screens at eye level prevents neck and back pain.'),
  ('Digital Well-being', 'If your daily LittleNet screen time limit is reached, what should you do?', 'Try to hack the parent password', 'Accept the break, enjoy your offline activities, and rest your eyes', 'Cry and throw the phone', 'Stay awake until midnight to try again', 'Accept the break, enjoy your offline activities, and rest your eyes', 'Screen limits help you maintain a healthy balance between tech and life.'),
  ('Digital Well-being', 'What is the best way to handle notifications when doing school homework?', 'Keep the phone buzzing next to your textbook', 'Put the device on silent or in another room until study is done', 'Check every chime immediately', 'Reply to all chats while doing math', 'Put the device on silent or in another room until study is done', 'Focusing without digital distractions helps you finish homework faster.'),
  ('Digital Well-being', 'Is what you see on social media always 100% real life?', 'Yes, everything posted is completely real', 'No, people often only share highlight reels, filters, and best moments', 'Every photo online is completely unedited', 'Everyone is always as happy as their profile picture', 'No, people often only share highlight reels, filters, and best moments', 'Remember that social media shows curated highlights, not the full reality of life.'),
  ('Digital Well-being', 'What should you do during family dinner time with digital devices?', 'Play games under the table', 'Put devices away and talk with your family about their day', 'Watch videos with headphones', 'Take photos of every bite of food', 'Put devices away and talk with your family about their day', 'Meal times are great opportunities for real-world connection and conversation.'),
  ('Digital Well-being', 'Why does LittleNet have a Brain Break quiz during Reels and Feed?', 'To trick you into failing', 'To pause continuous scrolling and give your brain a moment of mindfulness', 'Because the server runs out of video tapes', 'To test your speed typing', 'To pause continuous scrolling and give your brain a moment of mindfulness', 'Brain breaks encourage thoughtful engagement instead of endless passive scrolling.'),
  ('Digital Well-being', 'Who can you talk to if something online makes you feel uncomfortable or scared?', 'A stranger in a gaming chat', 'A trusted parent, teacher, school counselor, or family member', 'Nobody, you must hide it', 'Only an anonymous forum', 'A trusted parent, teacher, school counselor, or family member', 'Trusted adults care about you and can help solve any uncomfortable situation.')
) AS q(
  category, question, option_a, option_b, option_c, option_d,
  correct_answer, explanation
)
CROSS JOIN (VALUES ('6-8'), ('9-11'), ('12-13'), ('14-18')) AS age(age_group)
ON CONFLICT (question, age_group) DO UPDATE SET
  category = EXCLUDED.category,
  option_a = EXCLUDED.option_a,
  option_b = EXCLUDED.option_b,
  option_c = EXCLUDED.option_c,
  option_d = EXCLUDED.option_d,
  correct_answer = EXCLUDED.correct_answer,
  explanation = EXCLUDED.explanation;

-- migrate:down
-- Migration rollback intentionally preserves base bank
